### ISSUE TITLE
how to fetch previous messages in peer-to-peer chat

### ISSUE THREAD

**Issue by creativitycomkw** [ApiRTC/ApiRTC-examples#7]
i want to fetch previous messages of peer-to-peer chat but i am not able to find any api to do so.
please provide the solution asap

**Comment by creativitycomkw** [comment]
can anybody help?

**Comment by rvailleux** [comment]
hi @creativitycomkw 

Sorry for the TTL

Please, user stackoverflow with a reference to apirtc for support purpose. 
The git issues on the ApiRTC-example are dedicated to improvment suggestion only. 

thanks

Cheers, 

Romain
